create table if not exists public.studio_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'trial' check (plan in ('trial', 'owner', 'inactive')),
  trial_item_limit integer not null default 3 check (trial_item_limit >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.studio_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.studio_profiles(id) on delete cascade,
  client_item_id uuid not null,
  created_at timestamptz not null default now(),
  unique (user_id, client_item_id)
);

create table if not exists public.studio_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.studio_profiles(id) on delete cascade,
  item_id bigint not null references public.studio_items(id) on delete cascade,
  operation text not null check (operation in ('background_remove', 'listing_copy', 'creative_image')),
  status text not null default 'reserved' check (status in ('reserved', 'succeeded', 'failed')),
  provider text,
  model text,
  estimated_cost_micros integer check (estimated_cost_micros is null or estimated_cost_micros >= 0),
  provider_usage jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists studio_items_user_id_idx on public.studio_items(user_id);
create index if not exists studio_usage_events_user_id_idx on public.studio_usage_events(user_id);
create index if not exists studio_usage_events_item_id_idx on public.studio_usage_events(item_id);
create index if not exists studio_usage_events_item_operation_status_idx
  on public.studio_usage_events(item_id, operation, status);

alter table public.studio_profiles enable row level security;
alter table public.studio_items enable row level security;
alter table public.studio_usage_events enable row level security;

revoke all on table public.studio_profiles from anon, authenticated;
revoke all on table public.studio_items from anon, authenticated;
revoke all on table public.studio_usage_events from anon, authenticated;
grant all on table public.studio_profiles to service_role;
grant all on table public.studio_items to service_role;
grant all on table public.studio_usage_events to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.handle_new_studio_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.studio_profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_studio_profile on auth.users;
create trigger on_auth_user_created_studio_profile
  after insert on auth.users
  for each row execute procedure public.handle_new_studio_user();

insert into public.studio_profiles (id)
select id from auth.users
on conflict (id) do nothing;

create or replace function public.studio_authorize_operation(
  p_user_id uuid,
  p_is_owner boolean,
  p_client_item_id uuid default null,
  p_operation text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_profile public.studio_profiles%rowtype;
  v_item_id bigint;
  v_items_used integer := 0;
  v_operation_used integer := 0;
  v_operation_limit integer;
  v_reservation_id bigint;
  v_item_started boolean := false;
begin
  if p_user_id is null then
    return jsonb_build_object('allowed', false, 'reason', 'UNAUTHORIZED');
  end if;

  insert into public.studio_profiles (id, plan)
  values (p_user_id, case when p_is_owner then 'owner' else 'trial' end)
  on conflict (id) do update
    set plan = case when p_is_owner then 'owner' else public.studio_profiles.plan end,
        updated_at = now();

  select * into v_profile
  from public.studio_profiles
  where id = p_user_id
  for update;

  if v_profile.plan = 'inactive' then
    return jsonb_build_object('allowed', false, 'reason', 'ACCESS_DISABLED', 'plan', v_profile.plan);
  end if;

  select count(*)::integer into v_items_used
  from public.studio_items i
  where i.user_id = p_user_id
    and exists (
      select 1
      from public.studio_usage_events e
      where e.item_id = i.id
        and (e.status = 'succeeded' or (e.status = 'reserved' and e.created_at > now() - interval '15 minutes'))
    );

  if p_client_item_id is not null then
    select id into v_item_id
    from public.studio_items
    where user_id = p_user_id and client_item_id = p_client_item_id;

    if v_item_id is not null then
      select exists (
        select 1 from public.studio_usage_events
        where item_id = v_item_id
          and (status = 'succeeded' or (status = 'reserved' and created_at > now() - interval '15 minutes'))
      ) into v_item_started;
    end if;
  end if;

  if p_operation is null then
    return jsonb_build_object(
      'allowed', true,
      'owner', v_profile.plan = 'owner',
      'plan', v_profile.plan,
      'items_used', v_items_used,
      'item_limit', case when v_profile.plan = 'owner' then null else v_profile.trial_item_limit end,
      'items_remaining', case when v_profile.plan = 'owner' then null else greatest(0, v_profile.trial_item_limit - v_items_used) end,
      'current_item_started', v_item_started
    );
  end if;

  if p_client_item_id is null then
    return jsonb_build_object('allowed', false, 'reason', 'INVALID_ITEM');
  end if;

  if p_operation = 'background_remove' then
    v_operation_limit := 25;
  elsif p_operation = 'listing_copy' then
    v_operation_limit := 3;
  elsif p_operation = 'creative_image' then
    v_operation_limit := 2;
  else
    return jsonb_build_object('allowed', false, 'reason', 'INVALID_OPERATION');
  end if;

  if v_item_id is null then
    if v_profile.plan <> 'owner' and v_items_used >= v_profile.trial_item_limit then
      return jsonb_build_object(
        'allowed', false,
        'reason', 'TRIAL_EXHAUSTED',
        'owner', false,
        'plan', v_profile.plan,
        'items_used', v_items_used,
        'item_limit', v_profile.trial_item_limit,
        'items_remaining', 0,
        'current_item_started', false
      );
    end if;

    insert into public.studio_items (user_id, client_item_id)
    values (p_user_id, p_client_item_id)
    on conflict (user_id, client_item_id) do update set client_item_id = excluded.client_item_id
    returning id into v_item_id;
  end if;

  select count(*)::integer into v_operation_used
  from public.studio_usage_events
  where item_id = v_item_id
    and operation = p_operation
    and (status = 'succeeded' or (status = 'reserved' and created_at > now() - interval '15 minutes'));

  if v_profile.plan <> 'owner' and v_operation_used >= v_operation_limit then
    return jsonb_build_object(
      'allowed', false,
      'reason', 'OPERATION_LIMIT',
      'operation', p_operation,
      'operation_limit', v_operation_limit,
      'owner', false,
      'plan', v_profile.plan,
      'items_used', v_items_used,
      'item_limit', v_profile.trial_item_limit,
      'items_remaining', greatest(0, v_profile.trial_item_limit - v_items_used),
      'current_item_started', true
    );
  end if;

  insert into public.studio_usage_events (user_id, item_id, operation)
  values (p_user_id, v_item_id, p_operation)
  returning id into v_reservation_id;

  if not v_item_started then
    v_items_used := v_items_used + 1;
  end if;

  return jsonb_build_object(
    'allowed', true,
    'reservation_id', v_reservation_id,
    'owner', v_profile.plan = 'owner',
    'plan', v_profile.plan,
    'items_used', v_items_used,
    'item_limit', case when v_profile.plan = 'owner' then null else v_profile.trial_item_limit end,
    'items_remaining', case when v_profile.plan = 'owner' then null else greatest(0, v_profile.trial_item_limit - v_items_used) end,
    'current_item_started', true,
    'operation', p_operation,
    'operation_used', v_operation_used + 1,
    'operation_limit', case when v_profile.plan = 'owner' then null else v_operation_limit end
  );
end;
$$;

create or replace function public.studio_complete_usage(
  p_user_id uuid,
  p_reservation_id bigint,
  p_success boolean,
  p_provider text default null,
  p_model text default null,
  p_estimated_cost_micros integer default null,
  p_provider_usage jsonb default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.studio_usage_events
  set status = case when p_success then 'succeeded' else 'failed' end,
      provider = left(p_provider, 80),
      model = left(p_model, 160),
      estimated_cost_micros = p_estimated_cost_micros,
      provider_usage = p_provider_usage,
      completed_at = now()
  where id = p_reservation_id
    and user_id = p_user_id
    and status = 'reserved';
  return found;
end;
$$;

revoke all on function public.handle_new_studio_user() from public, anon, authenticated;
revoke all on function public.studio_authorize_operation(uuid, boolean, uuid, text) from public, anon, authenticated;
revoke all on function public.studio_complete_usage(uuid, bigint, boolean, text, text, integer, jsonb) from public, anon, authenticated;
grant execute on function public.studio_authorize_operation(uuid, boolean, uuid, text) to service_role;
grant execute on function public.studio_complete_usage(uuid, bigint, boolean, text, text, integer, jsonb) to service_role;
